# Introdução à Ciência de Dados - UFPB
Professor: Yuri Malheiros

## NumPy

Implemente a função `distance` abaixo. Ela deve receber dois pontos e retornar a distância euclidiana entre eles. Cada ponto é representado por um array do NumPy, por exemplo, `p1 = np.array([2,4])` representa o ponto com coordenadas x=2 e y=2.

In [9]:
import numpy as np

def distance(p1, p2):
    """
    >>> distance(np.array([0,0]), np.array([1,1]))
    1.4142135623730951
    
    >>> distance(np.array([1,2]), np.array([3,4]))
    2.8284271247461903
    
    >>> distance(np.array([5,2]), np.array([-2,-1]))
    7.615773105863909
    """
    
    # ADICIONE O SEU CÓDIGO AQUI
    return np.sqrt(np.sum((p1-p2)**2))

distance(np.array([5,2]), np.array([-2,-1]))

7.615773105863909

Implemente a função `n_distances` abaixo. Ela recebe um ponto (`p1`), como um array do NumPy, e uma lista de pontos (`points`), uma matriz do NumPy, onde cada linha representa um ponto.

Esta função deve retornar a distância de `p1` para todos os pontos da matriz `points`. O retorno também é uma matriz, onde cada linha tem a distância de `p1` para o ponto daquela linha.

In [24]:
def n_distances(p1, points):
    """
    >>> n_distances(np.array([0,0]), np.array([[1,1]]))
    array([1.41421356])
    
    >>> n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
    array([1.41421356, 2.82842712])
    
    >>> n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
    array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])
    """
    
    # ADICIONE O SEU CÓDIGO AQUI
    
    s = points
    p = p1
    lista = [np.sqrt((p[0]-s0)**2 + (p[1]-s1)**2) for s0, s1 in s]
    return lista

n_distances(np.array([0,0]), np.array([1,1], [2,2]))

TypeError: data type not understood

## Teste

In [17]:
import doctest

doctest.testmod(verbose=True)

Trying:
    distance(np.array([0,0]), np.array([1,1]))
Expecting:
    1.4142135623730951
ok
Trying:
    distance(np.array([1,2]), np.array([3,4]))
Expecting:
    2.8284271247461903
ok
Trying:
    distance(np.array([5,2]), np.array([-2,-1]))
Expecting:
    7.615773105863909
ok
Trying:
    n_distances(np.array([0,0]), np.array([[1,1]]))
Expecting:
    array([1.41421356])
**********************************************************************
File "__main__", line 3, in __main__.n_distances
Failed example:
    n_distances(np.array([0,0]), np.array([[1,1]]))
Expected:
    array([1.41421356])
Got:
    array([[1., 1.]])
Trying:
    n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
Expecting:
    array([1.41421356, 2.82842712])
**********************************************************************
File "__main__", line 6, in __main__.n_distances
Failed example:
    n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
Expected:
    array([1.41421356, 2.82842712])
Got:
    array([[1., 1.]

TestResults(failed=3, attempted=6)